# Trick-1; incase of initialization of collection data types always end it with comma. Its handly to check diff or
# review the code. However missing comma in the elements lead to concatenation of elements if they are of string type.
mylist = [
    'ABC',
    'DEF',
    'GHI',
]

print(mylist)

mylist1 = ['ABC', 'DEF','XYZ' 'WBC']

print "This concatenates the last two elements considering space as string, ", mylist1

mylist1 =  ['ABC', 'DEF',10 11]

print "Python throws SyntaxError exception as 10 and 11 integers cant be concatenate with space, ", mylist1

# Note: SyntaxError exception can be caught only if the SyntaxError is generated by Eval, Exec etc

